### ISSUE TITLE
Compatibility Issues with IsaacSim 2023, Orbit, TorchRL, and TensorDict

### ISSUE THREAD

**Issue by AkgunOnur** [btx0424/OmniDrones#44]
Dear Maintainers,

First and foremost, I would like to express my appreciation for your work on this repository. It exhibits significant potential, and our research group is keen on utilizing it for our project. Unfortunately, we have encountered compatibility issues during execution that we hope to resolve with your guidance.

**Environment Setup:**
- IsaacSim Version: 2023 Release
- Python Version: 3.10.13
- Installed Packages: OmniDrones, TensorDict, TorchRL (no errors during installation)
- Orbit Installation: Followed instructions from [Orbit Installation Guide](https://isaac-orbit.github.io/orbit/source/setup/installation.html#installing-orbit) (no errors, but received compatibility warnings)

**Issue Encountered:**
Upon attempting to execute the train.py script within the scripts folder, an error occurs:

`Error executing job with overrides: ['headless=true']
Traceback (most recent call last):
  File "/home/onur/Downloads/OmniDrones/scripts/train.py", line 128, in main
    ...
    AttributeError: 'Tensor' object has no attribute '_exclude'
`

This error suggests a compatibility issue between the Orbit package and the TorchRL and TensorDict libraries, which is impeding our progress.

Request for Assistance:
Could you provide any insights or solutions to address this compatibility issue? Any guidance or updates to resolve these conflicts would be greatly appreciated.

Thank you in advance for your time and assistance. We look forward to your response and hope to continue using this valuable resource for our research.

Best regards,

**Comment by SuuTTT** [comment]
same 
---
environment:
- install sim3.10-hotfix
- pip install tensordict torchrl
- pip install -e .
---
detail error

Error executing job with overrides: ['algo=ppo', 'headless=true', 'wandb.entity=user21']
Traceback (most recent call last):
  File "/home/user/OmniDrones/scripts/train.py", line 128, in main
    collector = SyncDataCollector(
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/collectors/collectors.py", line 721, in __init__
    self._shuttle = self.env.reset()
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/envs/common.py", line 2056, in reset
    tensordict_reset = self._reset(tensordict, **kwargs)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/envs/transforms/transforms.py", line 790, in _reset
    tensordict_reset = self.transform._reset(tensordict, tensordict_reset)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/envs/transforms/transforms.py", line 1050, in _reset
    tensordict_reset = t._reset(tensordict, tensordict_reset)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/envs/transforms/transforms.py", line 1050, in _reset
    tensordict_reset = t._reset(tensordict, tensordict_reset)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/envs/transforms/transforms.py", line 3775, in _reset
    tensordict_reset = self._call(tensordict_reset)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/torchrl/envs/transforms/transforms.py", line 3760, in _call
    tensordict.exclude(*self.keys_to_exclude, inplace=True)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/tensordict/base.py", line 4266, in exclude
    result = self._exclude(*keys, inplace=inplace)
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/tensordict/_td.py", line 1988, in _exclude
    val = val._exclude(
  File "/home/user/miniconda3/envs/sim3.10-hotfix/lib/python3.10/site-packages/tensordict/_td.py", line 1988, in _exclude
    val = val._exclude(
AttributeError: 'Tensor' object has no attribute '_exclude'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb:  View run Hover-ppo/02-10_01-36 at: https://wandb.ai/user21/omnidrones/runs/gigy0a7j
wandb: ️⚡ View job at https://wandb.ai/user21/omnidrones/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEzODUxOTk2Mg==/version_details/v0

**Comment by btx0424** [comment]
Sorry for the delayed reply! It should be fixed now.

**Comment by AkgunOnur** [comment]
Hi

Hope you're doing well. I'm still having a bit of a problem with TensorDict. I tried uninstalling it and then reinstalling it again, both with pip for the stable release and from the source using "python setup.py develop." But, I'm still stuck with this error:

`tensordict.exclude(*self.keys_to_exclude, inplace=True)
  File "/home/onur/Downloads/tensordict/tensordict/base.py", line 4343, in exclude
    result = self._exclude(*keys, inplace=inplace)
  File "/home/onur/Downloads/tensordict/tensordict/_td.py", line 2045, in _exclude
    val = val._exclude(
  File "/home/onur/Downloads/tensordict/tensordict/_td.py", line 2045, in _exclude
    val = val._exclude(
AttributeError: 'Tensor' object has no attribute '_exclude'`

I also tried version 0.4.0, thinking it might fix things. But it turns out it needs Torch 2.2.0, which doesn't play nice with Isaac Orbit and now I'm seeing compatibility issues.

Got any ideas on how to get around this problem? Would really appreciate your input.

Thanks a bunch!

**Comment by SuuTTT** [comment]
> 

I can train with the #46   above, i update those files directly.  
this is my commands:
  - install ISAAC SIM 2023.1.0-hotfix in GUI
  - conda create -n sim3.10 python=3.10 -y
  - conda activate sim3.10
  - cp -r conda_setup/etc $CONDA_PREFIX
  - conda activate sim3.10
  - pip install tensordict torchrl
  - pip install -e .
  - cd scripts
  - python train.py algo=ppo headless=true wandb.entity=
    
this is the video: https://wandb.ai/sudingli21/omnidrones/reports/recording-24-02-13-12-54-11---Vmlldzo2ODA2NzE2?accessToken=s6i773lhaaymtk69ntt641t22k3myzjtghuz1drekqk1v0v64g1wlhq4626rjop7

**Comment by btx0424** [comment]
> Hi
> 
> Hope you're doing well. I'm still having a bit of a problem with TensorDict. I tried uninstalling it and then reinstalling it again, both with pip for the stable release and from the source using "python setup.py develop." But, I'm still stuck with this error:
> 
> `tensordict.exclude(*self.keys_to_exclude, inplace=True) File "/home/onur/Downloads/tensordict/tensordict/base.py", line 4343, in exclude result = self._exclude(*keys, inplace=inplace) File "/home/onur/Downloads/tensordict/tensordict/_td.py", line 2045, in _exclude val = val._exclude( File "/home/onur/Downloads/tensordict/tensordict/_td.py", line 2045, in _exclude val = val._exclude( AttributeError: 'Tensor' object has no attribute '_exclude'`
> 
> I also tried version 0.4.0, thinking it might fix things. But it turns out it needs Torch 2.2.0, which doesn't play nice with Isaac Orbit and now I'm seeing compatibility issues.
> 
> Got any ideas on how to get around this problem? Would really appreciate your input.
> 
> Thanks a bunch!

Hi. I found that the problem was with the usage of `CatTensors` Transform for concatenating the intrinsic parameters together. in `train.py`. The PR should have fixed it. Just run `git pull` under `OmniDrones`.

**Comment by AkgunOnur** [comment]
It works now. Thanks for the help!
